### ISSUE TITLE
Cannot add Tado rooms to Homey

### ISSUE THREAD

**Issue by Klomar12** [abn/com.tado.community.home#5]
Hello,
I added your app to enhance my Tado X experience but I have a problem. I cannot add any of my Tado rooms to my Homey.

I can add the Home and set the values without any issue, but if I try to add the rooms it just says that there are no new devices available.

**Comment by abn** [comment]
Thanks for the report @Klomar12. The issue is that Tado changed their API for X devices. But good news is, support is being tested now, I should have a test version with proper Tado X support up in the next few days.

**Comment by Klomar12** [comment]
That's awesome thank you

**Comment by abn** [comment]
@Klomar12 can you try the new version of the app at https://homey.app/en-gb/app/com.tado.community.home/tado%C2%B0-Home-Manager/test/ please?

**Comment by Klomar12** [comment]
I installed it and the rooms were correctly detected, everythings seems to be working fine!
